// Assemble a gallery report from the ```html snippets in references/components.md, so the
// catalog agents read is exactly what the browser tests render. Run directly to write one:
//   node tests/gallery.mjs [dir]   (prints the gallery.html path; defaults to a temp folder)
import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import zlib from "node:zlib";
import { buildFile } from "../scripts/lib/build.mjs";
import { SKILL_DIR } from "../scripts/lib/runtime.mjs";
import { escapeHtml } from "../scripts/lib/scan.mjs";
import { isEntrypoint } from "../scripts/report.mjs";

// A small valid PNG (a phone-shaped card) so figures render without binary fixtures.
function screenshotPng(width = 240, height = 160) {
  const rows = [];
  for (let y = 0; y < height; y++) {
    const row = [0];
    for (let x = 0; x < width; x++) {
      const bar = y < 28;
      const card = y > 44 && y < 120 && x > 16 && x < width - 16;
      row.push(...(bar ? [33, 85, 207] : card ? [238, 240, 244] : [255, 255, 255]));
    }
    rows.push(Buffer.from(row));
  }
  const chunk = (type, data) => {
    const length = Buffer.alloc(4);
    length.writeUInt32BE(data.length);
    const body = Buffer.concat([Buffer.from(type), data]);
    const crc = Buffer.alloc(4);
    crc.writeUInt32BE(zlib.crc32(body));
    return Buffer.concat([length, body, crc]);
  };
  const header = Buffer.alloc(13);
  header.writeUInt32BE(width, 0);
  header.writeUInt32BE(height, 4);
  header.set([8, 2, 0, 0, 0], 8);
  return Buffer.concat([
    Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]),
    chunk("IHDR", header), chunk("IDAT", zlib.deflateSync(Buffer.concat(rows))), chunk("IEND", Buffer.alloc(0))
  ]);
}

export function gallerySource() {
  const catalog = readFileSync(path.join(SKILL_DIR, "references/components.md"), "utf8");
  const sections = [];
  const styles = [];
  let index = 0;
  for (const block of catalog.split(/^## /m).slice(1)) {
    const title = block.split("\n")[0].trim();
    const snippets = [...block.matchAll(/```html\n([\s\S]*?)```/g)].map((m) => m[1]);
    if (title === "Page skeleton") continue;
    const body = [];
    for (const snippet of snippets) {
      if (snippet.trim().startsWith("<style>")) styles.push(snippet.trim());
      else body.push(snippet.replace(/id="(q|f)1"/g, (match, prefix) => `id="${prefix}${prefix === "q" ? ++index : 1}"`));
    }
    const id = `c-${title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}`;
    sections.push(`<section id="${id}">\n<h2>${escapeHtml(title)}</h2>\n${body.join("\n")}</section>`);
  }
  const all = sections.join("\n");
  for (const [, target] of all.matchAll(/href="#([^"]+)"/g)) {
    if (!all.includes(`id="${target}"`) && !sections.some((s) => s.includes(`id="${target}"`))) {
      sections.push(`<section id="${target}">\n<h2>Anchor target: ${target}</h2>\n<p class="muted">Linked from a snippet above.</p></section>`);
    }
  }
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Component gallery</title>
${styles.join("\n")}
</head>
<body>
<header class="hero">
  <p class="eyebrow">html-report-builder</p>
  <h1>Component gallery</h1>
  <p class="lede">Every snippet from references/components.md, rendered with the shared runtime. Generated by tests/gallery.mjs.</p>
  <dl class="meta"><div><dt>Source</dt><dd>components.md</dd></div><div><dt>Purpose</dt><dd>Visual review and browser tests</dd></div></dl>
</header>
<main>
${sections.join("\n")}
</main>
</body>
</html>
`;
}

/** Write gallery.html (plus the screenshot it references) into dir and build it in place. */
export function writeGallery(dir) {
  mkdirSync(path.join(dir, "2026-10-03-sync-plan.assets"), { recursive: true });
  writeFileSync(path.join(dir, "2026-10-03-sync-plan.assets", "orders-mobile.png"), screenshotPng());
  const file = path.join(dir, "gallery.html");
  writeFileSync(file, gallerySource());
  buildFile(file);
  return file;
}

if (isEntrypoint(import.meta.url)) {
  const dir = path.resolve(process.argv[2] || mkdtempSync(path.join(os.tmpdir(), "hr-gallery-")));
  console.log(writeGallery(dir));
}
