// Assemble a report from every snippet in references/section-templates.md and a deck from every
// snippet in references/slide-templates.md, for tests and visual review. Run directly to write
// both: node tests/templates.mjs [dir]   (prints the two paths; defaults to a temp folder)
import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { buildFile } from "../scripts/lib/build.mjs";
import { SKILL_DIR } from "../scripts/lib/runtime.mjs";
import { isEntrypoint } from "../scripts/report.mjs";
import { screenshotPng } from "./gallery.mjs";

const snippets = (name) => [...readFileSync(path.join(SKILL_DIR, "references", name), "utf8").matchAll(/```html\n([\s\S]*?)```/g)].map((m) => m[1].trim());
const page = (title, attrs, body) => `<!doctype html>
<html lang="en"${attrs}>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${title}</title>
</head>
<body>
${body}
</body>
</html>
`;

export function sectionTemplatesSource() {
  return page("Section templates", ' data-template="findings" data-audience="internal"', `<header class="hero">
  <p class="eyebrow">html-report-builder</p>
  <h1>Section templates</h1>
  <p class="lede">Every snippet from references/section-templates.md. Generated by tests/templates.mjs.</p>
</header>
<main>
${snippets("section-templates.md").join("\n")}
</main>`);
}

export function slideTemplatesSource() {
  return page("Slide templates", ' data-template="slides" data-audience="client"', `<main class="deck">
${snippets("slide-templates.md").join("\n")}
</main>`);
}

/** Every relative image a source references, so tests can provide it. */
export const imagesIn = (source) => [...new Set([...source.matchAll(/<img[^>]*\bsrc="(?!data:|https?:)([^"]+)"/g)].map((m) => m[1]))];

/** Write sections.html and slides.html (plus the images they reference) into dir and build them. */
export function writeTemplates(dir, { build = true } = {}) {
  const files = {};
  for (const [name, source] of [["sections", sectionTemplatesSource()], ["slides", slideTemplatesSource()]]) {
    for (const image of imagesIn(source)) {
      mkdirSync(path.dirname(path.join(dir, image)), { recursive: true });
      writeFileSync(path.join(dir, image), screenshotPng(240, 420));
    }
    files[name] = path.join(dir, `${name}.html`);
    writeFileSync(files[name], source);
    if (build) buildFile(files[name]);
  }
  return files;
}

if (isEntrypoint(import.meta.url)) {
  const dir = path.resolve(process.argv[2] || mkdtempSync(path.join(os.tmpdir(), "hr-templates-")));
  mkdirSync(dir, { recursive: true });
  const files = writeTemplates(dir);
  console.log(`${files.sections}\n${files.slides}`);
}
